version: '3.4'

services:
  apigateway:
    build:
      context: .
      dockerfile: src/FabricDemo.ApiGateway/Dockerfile

  identityserver:
    build:
      context: .
      dockerfile: src/FabricDemo.IdentityServer/Dockerfile

  productservice:
    build:
      context: .
      dockerfile: src/FabricDemo.ProductService/Dockerfile

  userservice:
    build:
      context: .
      dockerfile: src/FabricDemo.UserService/Dockerfile