version: '3.4'

services:
  apigateway:
    image: fabricdemo/apigateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/FabricDemo.ApiGateway/Dockerfile

  identityserver:
    image: fabricdemo/identityserver:${TAG:-latest}
    build:
      context: .
      dockerfile: src/FabricDemo.IdentityServer/Dockerfile

  productservice:
    image: fabricdemo/productservice:${TAG:-latest}
    build:
      context: .
      dockerfile: src/FabricDemo.ProductService/Dockerfile

  userservice:
    image: fabricdemo/userservice:${TAG:-latest}
    build:
      context: .
      dockerfile: src/FabricDemo.UserService/Dockerfile