version: '3.4'

services:
  apigateway:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-study/fabricdemo-apigateway:0.1.0-pro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  identityserver:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-study/fabricdemo-identityserver:0.1.0-pro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  productservice:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-study/fabricdemo-productservice:0.1.0-pro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  userservice:
    image: registry.cn-shenzhen.aliyuncs.com/zengql-study/fabricdemo-userservice:0.1.0-pro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production