version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY}fabricdemo_apigateway
    build:
      context: .
      dockerfile: src/FabricDemo.ApiGateway/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY}fabricdemo_identityserver
    build:
      context: .
      dockerfile: src/FabricDemo.IdentityServer/Dockerfile

  productservice:
    image: ${DOCKER_REGISTRY}fabricdemo_productservice
    build:
      context: .
      dockerfile: src/FabricDemo.ProductService/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY}fabricdemo_userservice
    build:
      context: .
      dockerfile: src/FabricDemo.UserService/Dockerfile