version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY}fabricdemo_apigateway
    build:
      context: .
      dockerfile: src/FabricDemo.ApiGateway/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:54479
    ports:
      - "54479:54479"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identityserver:
    image: ${DOCKER_REGISTRY}fabricdemo_identityserver
    build:
      context: .
      dockerfile: src/FabricDemo.IdentityServer/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:54452
    ports:
      - "54452:54452"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  productservice:
    image: ${DOCKER_REGISTRY}fabricdemo_productservice
    build:
      context: .
      dockerfile: src/FabricDemo.ProductService/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:55121
    ports:
      - "55121:55121"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  userservice:
    image: ${DOCKER_REGISTRY}fabricdemo_userservice
    build:
      context: .
      dockerfile: src/FabricDemo.UserService/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:54045
    ports:
      - "54045:54045"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro